// Static travel data for all countries - generated by AI, updated with app versions
// Last updated: 2026-02-08

export interface TravelInfo {
  country: string;
  countryEn: string;
  documents: string;
  vaccinations: string;
  requirements: string;
  restrictions: string;
  recommendations: string;
  entryProcedure: string;
}

// All countries sorted alphabetically in Polish
export const COUNTRIES_PL = [
  "Afganistan", "Albania", "Algieria", "Andora", "Angola", "Antigua i Barbuda", "Arabia Saudyjska",
  "Argentyna", "Armenia", "Australia", "Austria", "Azerbejdżan", "Bahamy", "Bahrajn", "Bangladesz",
  "Barbados", "Belgia", "Belize", "Benin", "Bhutan", "Białoruś", "Boliwia", "Bośnia i Hercegowina",
  "Botswana", "Brazylia", "Brunei", "Bułgaria", "Burkina Faso", "Burundi", "Chile", "Chiny",
  "Chorwacja", "Cypr", "Czad", "Czarnogóra", "Czechy", "Dania", "Demokratyczna Republika Konga",
  "Dominika", "Dominikana", "Dżibuti", "Egipt", "Ekwador", "Erytrea", "Estonia", "Eswatini",
  "Etiopia", "Fidżi", "Filipiny", "Finlandia", "Francja", "Gabon", "Gambia", "Ghana", "Grecja",
  "Grenada", "Gruzja", "Gujana", "Gwatemala", "Gwinea", "Gwinea Bissau", "Gwinea Równikowa",
  "Haiti", "Hiszpania", "Holandia", "Honduras", "Indie", "Indonezja", "Irak", "Iran", "Irlandia",
  "Islandia", "Izrael", "Jamajka", "Japonia", "Jemen", "Jordania", "Kambodża", "Kamerun", "Kanada",
  "Katar", "Kazachstan", "Kenia", "Kirgistan", "Kiribati", "Kolumbia", "Komory", "Kongo", "Korea Południowa",
  "Korea Północna", "Kostaryka", "Kuba", "Kuwejt", "Laos", "Lesotho", "Liban", "Liberia", "Libia",
  "Liechtenstein", "Litwa", "Luksemburg", "Łotwa", "Macedonia Północna", "Madagaskar", "Malawi",
  "Malediwy", "Malezja", "Mali", "Malta", "Maroko", "Mauretania", "Mauritius", "Meksyk", "Mikronezja",
  "Mołdawia", "Monako", "Mongolia", "Mozambik", "Myanmar", "Namibia", "Nauru", "Nepal", "Niemcy",
  "Niger", "Nigeria", "Nikaragua", "Norwegia", "Nowa Zelandia", "Oman", "Pakistan", "Palau", "Panama",
  "Papua-Nowa Gwinea", "Paragwaj", "Peru", "Polska", "Portugalia", "Republika Południowej Afryki",
  "Republika Środkowoafrykańska", "Rosja", "Rumunia", "Rwanda", "Saint Kitts i Nevis", "Saint Lucia",
  "Saint Vincent i Grenadyny", "Salwador", "Samoa", "San Marino", "Senegal", "Serbia", "Seszele",
  "Sierra Leone", "Singapur", "Słowacja", "Słowenia", "Somalia", "Sri Lanka", "Stany Zjednoczone",
  "Sudan", "Sudan Południowy", "Surinam", "Syria", "Szwajcaria", "Szwecja", "Tadżykistan", "Tajlandia",
  "Tajwan", "Tanzania", "Timor Wschodni", "Togo", "Tonga", "Trynidad i Tobago", "Tunezja", "Turcja",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraina", "Urugwaj", "Uzbekistan", "Vanuatu", "Watykan",
  "Wenezuela", "Węgry", "Wielka Brytania", "Wietnam", "Włochy", "Wybrzeże Kości Słoniowej", "Wyspy Marshalla",
  "Wyspy Salomona", "Zambia", "Zimbabwe", "Zjednoczone Emiraty Arabskie"
];

export const COUNTRIES_EN = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Saudi Arabia",
  "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
  "Barbados", "Belgium", "Belize", "Benin", "Bhutan", "Belarus", "Bolivia", "Bosnia and Herzegovina",
  "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Chile", "China",
  "Croatia", "Cyprus", "Chad", "Montenegro", "Czech Republic", "Denmark", "Democratic Republic of the Congo",
  "Dominica", "Dominican Republic", "Djibouti", "Egypt", "Ecuador", "Eritrea", "Estonia", "Eswatini",
  "Ethiopia", "Fiji", "Philippines", "Finland", "France", "Gabon", "Gambia", "Ghana", "Greece",
  "Grenada", "Georgia", "Guyana", "Guatemala", "Guinea", "Guinea-Bissau", "Equatorial Guinea",
  "Haiti", "Spain", "Netherlands", "Honduras", "India", "Indonesia", "Iraq", "Iran", "Ireland",
  "Iceland", "Israel", "Jamaica", "Japan", "Yemen", "Jordan", "Cambodia", "Cameroon", "Canada",
  "Qatar", "Kazakhstan", "Kenya", "Kyrgyzstan", "Kiribati", "Colombia", "Comoros", "Congo", "South Korea",
  "North Korea", "Costa Rica", "Cuba", "Kuwait", "Laos", "Lesotho", "Lebanon", "Liberia", "Libya",
  "Liechtenstein", "Lithuania", "Luxembourg", "Latvia", "North Macedonia", "Madagascar", "Malawi",
  "Maldives", "Malaysia", "Mali", "Malta", "Morocco", "Mauritania", "Mauritius", "Mexico", "Micronesia",
  "Moldova", "Monaco", "Mongolia", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Germany",
  "Niger", "Nigeria", "Nicaragua", "Norway", "New Zealand", "Oman", "Pakistan", "Palau", "Panama",
  "Papua New Guinea", "Paraguay", "Peru", "Poland", "Portugal", "South Africa",
  "Central African Republic", "Russia", "Romania", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia",
  "Saint Vincent and the Grenadines", "El Salvador", "Samoa", "San Marino", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Somalia", "Sri Lanka", "United States",
  "Sudan", "South Sudan", "Suriname", "Syria", "Switzerland", "Sweden", "Tajikistan", "Thailand",
  "Taiwan", "Tanzania", "East Timor", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey",
  "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City",
  "Venezuela", "Hungary", "United Kingdom", "Vietnam", "Italy", "Ivory Coast", "Marshall Islands",
  "Solomon Islands", "Zambia", "Zimbabwe", "United Arab Emirates"
];

// Travel data - comprehensive information for each country
export const TRAVEL_DATA: Record<string, TravelInfo> = {
  // === EUROPA - KRAJE UE (wspólne zasady) ===
  "Austria": {
    country: "Austria",
    countryEn: "Austria",
    documents: "Paszport dla zwierząt domowych UE, mikrochip, ważne szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna - minimum 21 dni przed podróżą, ważne do 3 lat.",
    requirements: "Mikrochip zgodny z ISO 11784/11785, paszport UE dla zwierząt.",
    restrictions: "Zakaz wwozu ras uznanych za niebezpieczne (pitbulle, staffordy) do niektórych krajów związkowych. Maksymalnie 5 zwierząt na osobę.",
    recommendations: "Zabierz kopię dokumentacji weterynaryjnej. Upewnij się, że chip jest czytelny przed podróżą.",
    entryProcedure: "Swobodny przepływ w ramach UE. Kontrola dokumentów na granicy możliwa wyrywkowo."
  },
  "Belgia": {
    country: "Belgia",
    countryEn: "Belgium",
    documents: "Paszport UE dla zwierząt, mikrochip, aktualne szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Mikrochip, paszport UE, wiek minimum 15 tygodni.",
    restrictions: "Maksymalnie 5 zwierząt. Zakaz wwozu wilków i ich hybryd.",
    recommendations: "W Brukseli i innych miastach wymagany smycz w miejscach publicznych.",
    entryProcedure: "Swobodny przepływ UE, bez kontroli granicznych."
  },
  "Bułgaria": {
    country: "Bułgaria",
    countryEn: "Bulgaria",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa (21 dni - 12 miesięcy przed podróżą).",
    requirements: "Mikrochip ISO, paszport UE, zwierzę musi mieć minimum 15 tygodni.",
    restrictions: "Maksymalnie 5 zwierząt na osobę. Niektóre hotele nie przyjmują psów.",
    recommendations: "Unikaj podróżowania w upały - wysokie temperatury latem.",
    entryProcedure: "Kontrola dokumentów możliwa na granicy zewnętrznej UE."
  },
  "Chorwacja": {
    country: "Chorwacja",
    countryEn: "Croatia",
    documents: "Paszport UE dla zwierząt, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna - szczepienie ważne 21 dni przed wjazdem.",
    requirements: "Mikrochip, paszport UE, wiek minimum 15 tygodni.",
    restrictions: "Na plażach dla psów dozwolone, ale wiele plaż ma zakaz. Maksymalnie 5 zwierząt.",
    recommendations: "Wiele plaż dog-friendly, szczególnie na Istrii. Zabierz wodę pitną.",
    entryProcedure: "Swobodny przepływ w ramach UE/Schengen."
  },
  "Cypr": {
    country: "Cypr",
    countryEn: "Cyprus",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie, test miareczkowania (jeśli z kraju trzeciego).",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport UE. Dla psów spoza UE wymagany test serologiczny.",
    restrictions: "Kwarantanna dla psów z krajów wysokiego ryzyka. Zakaz ras niebezpiecznych.",
    recommendations: "Upały latem - zabierz dużo wody. Część północna (turecka) ma inne przepisy.",
    entryProcedure: "Kontrola dokumentów na lotnisku. Psy muszą lecieć jako cargo lub w kabinie (małe)."
  },
  "Czechy": {
    country: "Czechy",
    countryEn: "Czech Republic",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, ważna 21 dni - 12 miesięcy.",
    requirements: "Mikrochip ISO 11784, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. Psy muszą być na smyczy w miastach.",
    recommendations: "Praga bardzo przyjazna psom. Wiele restauracji i kawiarni akceptuje psy.",
    entryProcedure: "Swobodny przepływ w Schengen, brak kontroli granicznych z Polski."
  },
  "Dania": {
    country: "Dania",
    countryEn: "Denmark",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Mikrochip, paszport UE, wiek minimum 15 tygodni.",
    restrictions: "ZAKAZ 13 RAS: Pitbull terrier, Tosa, American Staffordshire Terrier, Fila Brasileiro, Dogo Argentino, American Bulldog, Boerboel, Kangal, Central Asian Shepherd, Caucasian Shepherd, South Russian Shepherd, Tornjak, Sarplaninac. Mieszańce tych ras również zakazane!",
    recommendations: "Sprawdź rasę psa przed wyjazdem - surowe kary za wwóz zakazanych ras.",
    entryProcedure: "Kontrola dokumentów możliwa na granicy. Wymagane jest przestrzeganie listy zakazanych ras."
  },
  "Estonia": {
    country: "Estonia",
    countryEn: "Estonia",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed podróżą.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt na osobę.",
    recommendations: "Tallin bardzo przyjazny psom. Lasy i parki narodowe często dopuszczają psy na smyczy.",
    entryProcedure: "Swobodny przepływ w Schengen."
  },
  "Finlandia": {
    country: "Finlandia",
    countryEn: "Finland",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie, leczenie przeciw tasiemcom (Echinococcus).",
    vaccinations: "Wścieklizna obowiązkowa. UWAGA: Wymagane odrobaczanie 1-5 dni przed wjazdem!",
    requirements: "Mikrochip, paszport UE, leczenie przeciw tasiemcom potwierdzone przez weterynarza.",
    restrictions: "Maksymalnie 5 zwierząt. Obowiązkowe odrobaczanie przed każdym wjazdem.",
    recommendations: "Zimą bardzo zimno - zabierz ciepłe ubranka dla psa. Latem uważaj na kleszcze.",
    entryProcedure: "Kontrola dokumentów możliwa. Sprawdzą odrobaczanie przeciw Echinococcus."
  },
  "Francja": {
    country: "Francja",
    countryEn: "France",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO 11784/11785, paszport weterynaryjny UE.",
    restrictions: "Kategoria 1 (psy d'attaque): Zakaz wwozu! Pitbulle, Boerboele bez rodowodu. Kategoria 2: Wymagane zaświadczenie o zachowaniu, kaganiec, smycz. Maksymalnie 5 zwierząt.",
    recommendations: "Wiele restauracji i hoteli przyjaznych psom. W metrze paryskim psy tylko w torbach transportowych (małe) lub z kagańcem (duże).",
    entryProcedure: "Swobodny przepływ UE. Kontrola dokumentów wyrywkowa."
  },
  "Grecja": {
    country: "Grecja",
    countryEn: "Greece",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE, wiek minimum 15 tygodni.",
    restrictions: "Maksymalnie 5 zwierząt. Na promach psy często muszą zostać w samochodzie lub w klatkach.",
    recommendations: "Bardzo gorące lato - zabierz dużo wody. Wiele tawern akceptuje psy. Plaże dla psów rzadkie.",
    entryProcedure: "Kontrola dokumentów na promach i lotniskach."
  },
  "Hiszpania": {
    country: "Hiszpania",
    countryEn: "Spain",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport UE. Niektóre regiony wymagają rejestracji ras niebezpiecznych.",
    restrictions: "8 ras potencjalnie niebezpiecznych wymaga specjalnego pozwolenia: Pitbull, Staffordshire, American Staffordshire, Rottweiler, Dogo Argentino, Fila Brasileiro, Tosa Inu, Akita Inu. Wymagane: ubezpieczenie OC, zaświadczenie o niekaralności, test psychologiczny właściciela.",
    recommendations: "Plaże dla psów popularne, szczególnie poza sezonem. Upały latem - nie zostawiaj psa w samochodzie!",
    entryProcedure: "Swobodny przepływ UE. Dla ras niebezpiecznych wymagane pozwolenie regionalne."
  },
  "Holandia": {
    country: "Holandia",
    countryEn: "Netherlands",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. Pitbulle i krzyżówki zakazane (ale egzekwowanie niejednorodne).",
    recommendations: "Bardzo przyjazny psom kraj. Amsterdam ma wiele parków i kawiarni dog-friendly.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Irlandia": {
    country: "Irlandia",
    countryEn: "Ireland",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie, leczenie przeciw tasiemcom.",
    vaccinations: "Wścieklizna obowiązkowa. OBOWIĄZKOWE odrobaczanie 1-5 dni przed wjazdem (Echinococcus).",
    requirements: "Mikrochip, paszport UE, leczenie przeciw tasiemcom wpisane w paszport.",
    restrictions: "Zakaz ras: American Pit Bull Terrier, English Bull Terrier, Staffordshire Bull Terrier, Bull Mastiff, Dobermann Pinscher, German Shepherd (Alsatian), Rhodesian Ridgeback, Rottweiler, Japanese Akita, Japanese Tosa i ich krzyżówki. Te rasy muszą nosić kaganiec i być na smyczy w miejscach publicznych.",
    recommendations: "Wiele pubów i restauracji przyjaznych psom. Piękne trasy spacerowe.",
    entryProcedure: "Kontrola dokumentów możliwa. Szczególna uwaga na odrobaczanie."
  },
  "Litwa": {
    country: "Litwa",
    countryEn: "Lithuania",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt na osobę.",
    recommendations: "Wilno przyjazne psom. Mierzeja Kurońska - piękne plaże, psy dozwolone poza sezonem.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Luksemburg": {
    country: "Luksemburg",
    countryEn: "Luxembourg",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport UE.",
    restrictions: "Maksymalnie 5 zwierząt. Rasy niebezpieczne wymagają pozwolenia.",
    recommendations: "Mały kraj, łatwo przemieszczać się z psem. Wiele parków.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Łotwa": {
    country: "Łotwa",
    countryEn: "Latvia",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed podróżą.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt.",
    recommendations: "Ryga przyjazna psom. Plaże bałtyckie często dopuszczają psy poza sezonem.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Malta": {
    country: "Malta",
    countryEn: "Malta",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie, test miareczkowania (dla niektórych przypadków).",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport UE. Dla psów latających - dodatkowe wymogi linii lotniczych.",
    restrictions: "Rasy niebezpieczne (Pit Bull, Dogo Argentino, Fila Brasileiro, Japanese Tosa) wymagają specjalnego pozwolenia.",
    recommendations: "Mała wyspa, gorące lata. Transport promem lub samolotem.",
    entryProcedure: "Kontrola dokumentów na lotnisku/w porcie."
  },
  "Niemcy": {
    country: "Niemcy",
    countryEn: "Germany",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem, ważne do 3 lat.",
    requirements: "Mikrochip ISO 11784/11785, paszport weterynaryjny UE.",
    restrictions: "Zakaz importu: Pit Bull Terrier, American Staffordshire Terrier, Staffordshire Bull Terrier, Bull Terrier i ich krzyżówki. Każdy land ma dodatkowe regulacje! W Bawarii i innych landach wymagany test charakteru i pozwolenie dla ras kategorialnych.",
    recommendations: "Bardzo przyjazny psom kraj. Wiele restauracji, hoteli i sklepów akceptuje psy. Pociągi DB pozwalają na przewóz psów (bilety dla dużych psów).",
    entryProcedure: "Swobodny przepływ Schengen, brak kontroli z Polski. Kontrole wyrywkowe możliwe."
  },
  "Polska": {
    country: "Polska",
    countryEn: "Poland",
    documents: "Paszport UE dla zwierząt, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, szczepienie ważne przez okres określony przez producenta (do 3 lat).",
    requirements: "Mikrochip ISO 11784/11785, paszport weterynaryjny UE wydany przez upoważnionego lekarza.",
    restrictions: "Maksymalnie 5 zwierząt na osobę. Niektóre miasta mają lokalne przepisy dotyczące ras agresywnych (wymagany kaganiec i smycz).",
    recommendations: "Wiele parków narodowych nie pozwala na psy. Sprawdź regulaminy przed wizytą.",
    entryProcedure: "Kraj macierzysty - brak specjalnych procedur wjazdowych."
  },
  "Portugalia": {
    country: "Portugalia",
    countryEn: "Portugal",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Rasy potencjalnie niebezpieczne wymagają rejestracji i pozwolenia: Staffordshire Bull Terrier, American Staffordshire Terrier, Rottweiler, Dogo Argentino, Fila Brasileiro, Pit Bull Terrier, Tosa Inu.",
    recommendations: "Wiele plaż dla psów, szczególnie poza sezonem. Lizbona przyjazna psom - tramwaje akceptują małe psy.",
    entryProcedure: "Swobodny przepływ UE."
  },
  "Rumunia": {
    country: "Rumunia",
    countryEn: "Romania",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. Rasy niebezpieczne wymagają kagańca w miejscach publicznych.",
    recommendations: "Transylwania ma piękne trasy górskie. Uważaj na bezpańskie psy w miastach.",
    entryProcedure: "Kontrola dokumentów możliwa na granicy (poza Schengen do 2024)."
  },
  "Słowacja": {
    country: "Słowacja",
    countryEn: "Slovakia",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed podróżą.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. Niektóre rasy wymagają kagańca w miastach.",
    recommendations: "Tatry słowackie - sprawdź regulaminy parków narodowych. Bratysława przyjazna psom.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Słowenia": {
    country: "Słowenia",
    countryEn: "Slovenia",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. W miejscach publicznych psy na smyczy.",
    recommendations: "Piękne Alpy Julijskie, jezioro Bled. Wiele szlaków dog-friendly.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Szwecja": {
    country: "Szwecja",
    countryEn: "Sweden",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE. UWAGA: Psy poniżej 15 tygodni NIE mogą wjechać.",
    restrictions: "Maksymalnie 5 zwierząt. Brak zakazu konkretnych ras, ale agresywne psy mogą być skonfiskowane.",
    recommendations: "Bardzo przyjazny psom kraj. Prawo allemansrätten pozwala na swobodne wędrówki po przyrodzie.",
    entryProcedure: "Swobodny przepływ Schengen, ale kontrole dokumentów możliwe."
  },
  "Węgry": {
    country: "Węgry",
    countryEn: "Hungary",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Maksymalnie 5 zwierząt. Rasy niebezpieczne wymagają kagańca.",
    recommendations: "Budapeszt przyjazny psom. Balaton - wiele plaż dla psów.",
    entryProcedure: "Swobodny przepływ Schengen."
  },
  "Włochy": {
    country: "Włochy",
    countryEn: "Italy",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Wymagany kaganiec (do noszenia) i smycz (max 1.5m) we wszystkich miejscach publicznych. Maksymalnie 5 zwierząt.",
    recommendations: "Włochy bardzo przyjazne psom! Restauracje, kawiarnie, wiele hoteli akceptuje psy. Plaże dla psów popularne.",
    entryProcedure: "Swobodny przepływ Schengen."
  },

  // === EUROPA - POZA UE ===
  "Norwegia": {
    country: "Norwegia",
    countryEn: "Norway",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie, leczenie przeciw tasiemcom (Echinococcus).",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem. OBOWIĄZKOWE odrobaczanie 1-5 dni przed wjazdem!",
    requirements: "Mikrochip ISO, paszport UE, leczenie przeciw tasiemcom wpisane przez weterynarza 24-120 godzin przed wjazdem.",
    restrictions: "Zakaz ras: Pit Bull Terrier, American Staffordshire Terrier, Fila Brasileiro, Tosa Inu, Dogo Argentino, Czechoslovakian Wolfdog i krzyżówki. Maksymalnie 5 zwierząt.",
    recommendations: "Piękne szlaki górskie i fiordy. Psy mile widziane w naturze, ale na smyczy w sezonie lęgowym.",
    entryProcedure: "Kontrola dokumentów na granicy. Sprawdzą odrobaczanie - brak wpisu = odmowa wjazdu!"
  },
  "Szwajcaria": {
    country: "Szwajcaria",
    countryEn: "Switzerland",
    documents: "Paszport UE, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, 21 dni przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny UE.",
    restrictions: "Każdy kanton ma własne przepisy! Niektóre kantony zakazują ras: Pit Bull, Bandog, American Staffordshire. W Genewie i Zurychu wymagane pozwolenia dla niektórych ras.",
    recommendations: "Bardzo drogi kraj. Góry i szlaki wspaniałe dla psów. Koleje SBB pozwalają na psy (bilety).",
    entryProcedure: "Schengen, ale kontrole możliwe. Sprawdź przepisy kantonu docelowego!"
  },
  "Wielka Brytania": {
    country: "Wielka Brytania",
    countryEn: "United Kingdom",
    documents: "Paszport UE dla zwierząt (wydany przed 2021) LUB świadectwo zdrowia zwierzęcia (AHC), mikrochip, szczepienie przeciw wściekliźnie, leczenie przeciw tasiemcom.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem. Odrobaczanie 1-5 dni przed wjazdem OBOWIĄZKOWE.",
    requirements: "Po Brexicie: wymagane Animal Health Certificate (AHC) wydane max 10 dni przed podróżą. Mikrochip, szczepienie, odrobaczanie.",
    restrictions: "ZAKAZ CAŁKOWITY: Pit Bull Terrier, Japanese Tosa, Dogo Argentino, Fila Brasileiro. Psy tych ras będą skonfiskowane i mogą być uśpione! Maksymalnie 5 zwierząt.",
    recommendations: "Wiele parków, pubów i hoteli przyjaznych psom. Londyn bardzo dog-friendly.",
    entryProcedure: "Wjazd tylko autoryzowanymi trasami (promy, Eurotunel z Dover/Calais, wybrane lotniska). Kontrola dokumentów obowiązkowa."
  },
  "Islandia": {
    country: "Islandia",
    countryEn: "Iceland",
    documents: "Pozwolenie importowe z MAST (Icelandic Food and Veterinary Authority), paszport UE, mikrochip, szczepienia.",
    vaccinations: "Wścieklizna, nosówka, parwowiroza, adenowirus - wszystkie wymagane. Leczenie przeciw pasożytom.",
    requirements: "KWARANTANNA OBOWIĄZKOWA! Minimum 2 tygodnie w specjalnym ośrodku (Keldur). Wymagane wcześniejsze pozwolenie (wniosek 6-8 tygodni wcześniej).",
    restrictions: "Bardzo restrykcyjne przepisy ze względu na izolację wyspy. Nie zaleca się krótkich podróży z psem.",
    recommendations: "Ze względu na kwarantannę, rozważ czy podróż z psem ma sens. Przepisy chronią rodzime ekosystemy.",
    entryProcedure: "Pozwolenie importowe, 2-tygodniowa kwarantanna w Keldur, testy laboratoryjne."
  },
  "Serbia": {
    country: "Serbia",
    countryEn: "Serbia",
    documents: "Paszport UE lub świadectwo zdrowia, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni i maximum 12 miesięcy przed wjazdem.",
    requirements: "Mikrochip ISO, paszport weterynaryjny lub świadectwo zdrowia (max 10 dni przed podróżą).",
    restrictions: "Maksymalnie 5 zwierząt na osobę.",
    recommendations: "Belgrad przyjazny psom. Przejścia graniczne mogą mieć kolejki - przygotuj dokumenty.",
    entryProcedure: "Kontrola dokumentów na granicy. Świadectwo zdrowia musi być w języku serbskim lub angielskim."
  },
  "Ukraina": {
    country: "Ukraina",
    countryEn: "Ukraine",
    documents: "Świadectwo zdrowia zwierzęcia (międzynarodowe), mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 30 dni i maximum 12 miesięcy przed wjazdem. Nosówka, parwowiroza zalecane.",
    requirements: "Międzynarodowe świadectwo weterynaryjne (Formularz 1), mikrochip ISO, szczepienia.",
    restrictions: "Maksymalnie 2 zwierzęta na osobę bez opłat celnych. Ze względu na wojnę - sprawdź aktualną sytuację!",
    recommendations: "UWAGA: Trwa konflikt zbrojny. Sprawdź aktualne ostrzeżenia MSZ przed podróżą.",
    entryProcedure: "Kontrola dokumentów i weterynaryjna na granicy."
  },
  "Turcja": {
    country: "Turcja",
    countryEn: "Turkey",
    documents: "Świadectwo zdrowia, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem. Zalecane: nosówka, parwowiroza, leptospiroza.",
    requirements: "Mikrochip ISO, międzynarodowe świadectwo zdrowia wydane max 10 dni przed podróżą.",
    restrictions: "Niektóre hotele nie akceptują psów. Zakaz ras: Pit Bull, Dogo Argentino, Japanese Tosa, Fila Brasileiro.",
    recommendations: "Hotele i restauracje często nie przyjazne psom - sprawdź przed wyjazdem. Upały latem.",
    entryProcedure: "Kontrola dokumentów na lotnisku lub granicy lądowej."
  },

  // === AMERYKA PÓŁNOCNA ===
  "Stany Zjednoczone": {
    country: "Stany Zjednoczone",
    countryEn: "United States",
    documents: "Świadectwo zdrowia, mikrochip zalecany, szczepienie przeciw wściekliźnie, pozwolenie CDC dla niektórych krajów.",
    vaccinations: "Wścieklizna obowiązkowa (stan zależy od stanu). Szczepienie minimum 28 dni przed wjazdem.",
    requirements: "Psy z krajów wysokiego ryzyka wścieklizny wymagają pozwolenia CDC i badań serologicznych. Polska NIE jest na liście wysokiego ryzyka.",
    restrictions: "Każdy stan ma własne przepisy! Hawaje wymagają kwarantanny. Niektóre stany zakazują ras. Zakaz wwozu psów poniżej 6 miesięcy z krajów ryzyka.",
    recommendations: "Sprawdź przepisy stanowe. Linie lotnicze mają różne wymagania dla psów w kabinie/cargo.",
    entryProcedure: "Kontrola na lotnisku przez CBP. Psy mogą być poddane inspekcji weterynaryjnej."
  },
  "Kanada": {
    country: "Kanada",
    countryEn: "Canada",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie (dla psów powyżej 3 miesięcy).",
    vaccinations: "Wścieklizna wymagana dla psów powyżej 3 miesięcy, minimum 28 dni przed wjazdem.",
    requirements: "Certyfikat weterynaryjny potwierdzający szczepienie przeciw wściekliźnie. Mikrochip zalecany.",
    restrictions: "Prowincje mogą mieć własne przepisy. Ontario zakazuje pit bulli. Maksymalnie 2 psy bez dodatkowych opłat.",
    recommendations: "Bardzo przyjazny psom kraj. Parki narodowe mają różne zasady - sprawdź przed wizytą.",
    entryProcedure: "Kontrola CFIA na granicy. Świadectwo zdrowia w języku angielskim lub francuskim."
  },
  "Meksyk": {
    country: "Meksyk",
    countryEn: "Mexico",
    documents: "Świadectwo zdrowia wydane max 10 dni przed podróżą, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, odrobaczanie zalecane.",
    requirements: "Świadectwo zdrowia z podpisem weterynarza, szczepienie przeciw wściekliźnie.",
    restrictions: "Maksymalnie 2 zwierzęta na osobę. Niektóre linie lotnicze nie przewożą psów ras brachycefalicznych.",
    recommendations: "Upały mogą być niebezpieczne dla psów. Wiele hoteli pet-friendly w kurortach.",
    entryProcedure: "Kontrola dokumentów przez SENASICA na lotnisku."
  },

  // === AMERYKA POŁUDNIOWA ===
  "Argentyna": {
    country: "Argentyna",
    countryEn: "Argentina",
    documents: "Świadectwo zdrowia międzynarodowe, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 15 dni i maximum 12 miesięcy przed wjazdem.",
    requirements: "Świadectwo zdrowia legalizowane przez SENASA. Mikrochip ISO.",
    restrictions: "Brak zakazu ras. Limit 3 zwierzęta na osobę.",
    recommendations: "Buenos Aires przyjazne psom. Wiele parków i kawiarni dog-friendly.",
    entryProcedure: "Kontrola przez SENASA na lotnisku."
  },
  "Brazylia": {
    country: "Brazylia",
    countryEn: "Brazil",
    documents: "Świadectwo zdrowia międzynarodowe, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem. Zalecane: nosówka, parwowiroza.",
    requirements: "Świadectwo zdrowia wydane max 10 dni przed podróżą, legalizowane. Mikrochip.",
    restrictions: "Maksymalnie 2 zwierzęta. Loty mogą być problematyczne w upały - embargo termiczne.",
    recommendations: "Wiele plaż zakazuje psów. Sprawdź lokalne przepisy. Rio ma kilka plaż dog-friendly.",
    entryProcedure: "Kontrola dokumentów przez VIGIAGRO na lotnisku."
  },
  "Chile": {
    country: "Chile",
    countryEn: "Chile",
    documents: "Świadectwo zdrowia, mikrochip, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Świadectwo zdrowia legalizowane przez SAG chilijski. Mikrochip ISO.",
    restrictions: "Maksymalnie 2 zwierzęta. Brak zakazu ras.",
    recommendations: "Patagonia piękna dla psów. Wiele hoteli akceptuje zwierzęta.",
    entryProcedure: "Kontrola SAG na lotnisku."
  },
  "Kolumbia": {
    country: "Kolumbia",
    countryEn: "Colombia",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane: nosówka, parwowiroza, leptospiroza.",
    requirements: "Świadectwo zdrowia wydane max 10 dni przed podróżą.",
    restrictions: "Rasy potencjalnie niebezpieczne wymagają rejestracji (Pit Bull, Rottweiler, American Staffordshire).",
    recommendations: "Upały w niższych rejonach. Bogota przyjazna psom.",
    entryProcedure: "Kontrola przez ICA na lotnisku."
  },
  "Peru": {
    country: "Peru",
    countryEn: "Peru",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie, mikrochip zalecany.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Świadectwo zdrowia legalizowane przez SENASA Peru.",
    restrictions: "Niektóre rasy wymagają pozwolenia. Limit 2 zwierzęta.",
    recommendations: "Wysokość (Lima, Cusco) może wpływać na psy. Machu Picchu zakazuje zwierząt.",
    entryProcedure: "Kontrola dokumentów przez SENASA."
  },

  // === AZJA ===
  "Japonia": {
    country: "Japonia",
    countryEn: "Japan",
    documents: "Zaświadczenie o zdrowiu, test miareczkowania, 180-dniowy okres oczekiwania.",
    vaccinations: "Wścieklizna - 2 szczepienia wymagane. Test miareczkowania obowiązkowy.",
    requirements: "BARDZO RESTRYKCYJNE: 1) Mikrochip przed pierwszym szczepieniem, 2) Dwa szczepienia przeciw wściekliźnie, 3) Test miareczkowania w akredytowanym laboratorium, 4) 180 dni oczekiwania od testu, 5) Zgłoszenie 40 dni przed przylotem.",
    restrictions: "Kwarantanna do 180 dni jeśli wymogi nie są spełnione! Brak zakazu ras.",
    recommendations: "Zacznij przygotowania 7-8 miesięcy przed wyjazdem! Hotele rzadko akceptują psy.",
    entryProcedure: "Inspekcja w Animal Quarantine Service na lotnisku. Przygotuj wszystkie dokumenty."
  },
  "Korea Południowa": {
    country: "Korea Południowa",
    countryEn: "South Korea",
    documents: "Świadectwo zdrowia, test miareczkowania, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa (2 dawki). Test miareczkowania wymagany.",
    requirements: "Mikrochip, szczepienie (2x), test miareczkowania, świadectwo zdrowia. Zgłoszenie do APQA.",
    restrictions: "Kwarantanna jeśli wymogi nie spełnione. Limit 5 zwierząt.",
    recommendations: "Seul ma wiele kawiarni dla psów. Hotele rzadziej akceptują duże psy.",
    entryProcedure: "Kontrola w Animal Plant Quarantine Agency."
  },
  "Chiny": {
    country: "Chiny",
    countryEn: "China",
    documents: "Świadectwo zdrowia, test miareczkowania, szczepienie, pozwolenie importowe.",
    vaccinations: "Wścieklizna obowiązkowa. Test miareczkowania z akredytowanego laboratorium.",
    requirements: "BARDZO SKOMPLIKOWANE: Pozwolenie importowe, mikrochip, szczepienia, test miareczkowania, 30-dniowa kwarantanna możliwa.",
    restrictions: "Limit 1 psa lub kota na osobę! Kwarantanna 30 dni (7-30 w zależności od miasta). Niektóre miasta zakazują dużych psów (np. powyżej 35cm w Pekinie).",
    recommendations: "Bardzo trudne przepisy. Rozważ czy warto zabierać psa. Hotele rzadko akceptują.",
    entryProcedure: "Kontrola celna i kwarantanna. Przygotuj się na długi proces."
  },
  "Tajlandia": {
    country: "Tajlandia",
    countryEn: "Thailand",
    documents: "Świadectwo zdrowia, pozwolenie importowe, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Pozwolenie importowe z DLD (Department of Livestock Development). Świadectwo zdrowia max 10 dni przed podróżą.",
    restrictions: "Pit Bull, American Staffordshire, Staffordshire Bull Terrier, American Pit Bull zakazane! Kwarantanna możliwa.",
    recommendations: "Upały mogą być niebezpieczne. Wiele kurortów nie akceptuje psów.",
    entryProcedure: "Kontrola w Livestock Quarantine Station na lotnisku."
  },
  "Wietnam": {
    country: "Wietnam",
    countryEn: "Vietnam",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie, pozwolenie importowe.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane: nosówka, parwowiroza.",
    requirements: "Świadectwo zdrowia legalizowane. Pozwolenie importowe wymagane.",
    restrictions: "Kwarantanna możliwa. Limit 2 zwierzęta.",
    recommendations: "Wiele hoteli nie akceptuje psów. Podróżowanie z psem może być trudne.",
    entryProcedure: "Kontrola weterynaryjna na lotnisku."
  },
  "Indie": {
    country: "Indie",
    countryEn: "India",
    documents: "Zezwolenie NOC, świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem. Zalecane inne szczepienia.",
    requirements: "NOC (No Objection Certificate) z AQCS. Świadectwo zdrowia. Mikrochip.",
    restrictions: "Kwarantanna domowa możliwa. Brak oficjalnego zakazu ras.",
    recommendations: "Upały mogą być niebezpieczne. Wiele miejsc nie akceptuje psów. Loty cargo preferowane dla dużych psów.",
    entryProcedure: "Kontrola AQCS na lotnisku. NOC wymagane przed przylotem."
  },
  "Indonezja": {
    country: "Indonezja",
    countryEn: "Indonesia",
    documents: "Pozwolenie importowe, świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Odrobaczanie wymagane.",
    requirements: "Pozwolenie importowe z Ministerstwa Rolnictwa. Kwarantanna 7-14 dni na Bali lub w Dżakarcie.",
    restrictions: "Bali wolne od wścieklizny - dodatkowe wymogi! Kwarantanna obowiązkowa.",
    recommendations: "Na Bali kwarantanna 7-14 dni. Rozważ czy warto. Hotele rzadko akceptują psy.",
    entryProcedure: "Kwarantanna w Animal Quarantine Station."
  },
  "Malezja": {
    country: "Malezja",
    countryEn: "Malaysia",
    documents: "Pozwolenie importowe, świadectwo zdrowia, test miareczkowania.",
    vaccinations: "Wścieklizna obowiązkowa. Test miareczkowania wymagany.",
    requirements: "Pozwolenie importowe. Kwarantanna minimum 7 dni.",
    restrictions: "Kwarantanna 7-30 dni w zależności od dokumentacji. Limit 2 zwierzęta.",
    recommendations: "Hotele rzadko akceptują psy. Upały wysokie. Kwarantanna kosztowna.",
    entryProcedure: "Kwarantanna obowiązkowa w Veterinary Quarantine Station."
  },
  "Singapur": {
    country: "Singapur",
    countryEn: "Singapore",
    documents: "Pozwolenie importowe AVS, świadectwo zdrowia, test miareczkowania.",
    vaccinations: "Wścieklizna obowiązkowa. Test miareczkowania wymagany.",
    requirements: "Pozwolenie importowe z AVS (Agri-Food & Veterinary Authority). Kwarantanna możliwa dla krajów kategorii B/C/D.",
    restrictions: "Kwarantanna 10-30 dni. Polska - kategoria B (kwarantanna min. 10 dni). Zakaz ras: Pit Bull, Akita, Boerboel, Tosa, Dogo Argentino, Fila Brasileiro, Neapolitan Mastiff.",
    recommendations: "Bardzo surowe przepisy. Kwarantanna kosztowna. Rozważ czy warto.",
    entryProcedure: "Kontrola i kwarantanna w Animal & Bird Centre."
  },
  "Filipiny": {
    country: "Filipiny",
    countryEn: "Philippines",
    documents: "Pozwolenie importowe, świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane inne szczepienia.",
    requirements: "Pozwolenie z Bureau of Animal Industry. Świadectwo zdrowia.",
    restrictions: "Kwarantanna możliwa. Limit 3 zwierzęta.",
    recommendations: "Upały wysokie. Wiele hoteli nie akceptuje psów.",
    entryProcedure: "Kontrola weterynaryjna na lotnisku."
  },
  "Zjednoczone Emiraty Arabskie": {
    country: "Zjednoczone Emiraty Arabskie",
    countryEn: "United Arab Emirates",
    documents: "Pozwolenie importowe, świadectwo zdrowia, test miareczkowania, mikrochip.",
    vaccinations: "Wścieklizna obowiązkowa. Test miareczkowania wymagany.",
    requirements: "Pozwolenie z Ministry of Climate Change. Test miareczkowania min. 3 miesiące przed podróżą.",
    restrictions: "Zakaz importu: Pit Bull, wszystkie mieszańce pit bulli. Limit 2 zwierzęta. Duże psy mogą mieć ograniczenia w mieszkaniach.",
    recommendations: "Dubaj przyjazny psom w porównaniu z innymi krajami arabskimi. Upały mogą być niebezpieczne.",
    entryProcedure: "Kontrola i możliwa kwarantanna 48h."
  },

  // === OCEANIA ===
  "Australia": {
    country: "Australia",
    countryEn: "Australia",
    documents: "Pozwolenie importowe, test miareczkowania, minimum 180 dni oczekiwania, kwarantanna.",
    vaccinations: "Wścieklizna - szczepienie i test miareczkowania. Kompleksowe odrobaczanie.",
    requirements: "JEDNE Z NAJSUROWSZYCH NA ŚWIECIE: 1) Mikrochip, 2) Szczepienie przeciw wściekliźnie, 3) Test miareczkowania min. 180 dni przed, 4) Wiele badań i leczenia, 5) 10-dniowa kwarantanna po przylocie.",
    restrictions: "10 dni kwarantanny obowiązkowej (opłata ~2000 AUD). Zakaz ras: Pit Bull, Dogo Argentino, Fila Brasileiro, Japanese Tosa, Presa Canario. Import tylko z wybranych krajów!",
    recommendations: "Zacznij przygotowania 8-12 miesięcy wcześniej! Bardzo kosztowny i skomplikowany proces.",
    entryProcedure: "Wjazd tylko przez Melbourne lub Sydney. 10 dni kwarantanny w Mickleham lub Eastern Creek."
  },
  "Nowa Zelandia": {
    country: "Nowa Zelandia",
    countryEn: "New Zealand",
    documents: "Pozwolenie importowe MPI, test miareczkowania, 180 dni oczekiwania, kwarantanna.",
    vaccinations: "Wścieklizna - szczepienie i test miareczkowania. Odrobaczanie przed podróżą.",
    requirements: "BARDZO RESTRYKCYJNE: 1) Pozwolenie MPI, 2) Mikrochip, 3) Szczepienia, 4) Test miareczkowania min. 180 dni przed, 5) Kwarantanna 10 dni.",
    restrictions: "10 dni kwarantanny obowiązkowej w Auckland. Zakaz ras: Pit Bull, Dogo Argentino, Fila Brasileiro, Japanese Tosa.",
    recommendations: "Przygotowania 8-12 miesięcy wcześniej. Kwarantanna kosztowna (~2000 NZD).",
    entryProcedure: "Wjazd tylko przez Auckland. Kwarantanna w Mangere."
  },

  // === AFRYKA ===
  "Egipt": {
    country: "Egipt",
    countryEn: "Egypt",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Świadectwo zdrowia legalizowane przez egipski konsulat.",
    restrictions: "Brak oficjalnego zakazu ras. Kwarantanna rzadka.",
    recommendations: "Upały mogą być niebezpieczne. Hotele przy plażach często nie akceptują psów.",
    entryProcedure: "Kontrola weterynaryjna na lotnisku."
  },
  "Maroko": {
    country: "Maroko",
    countryEn: "Morocco",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane odrobaczanie.",
    requirements: "Świadectwo zdrowia z legalizacją konsularną.",
    restrictions: "Brak oficjalnego zakazu ras. Psy w samochodach na promach.",
    recommendations: "Popularny kierunek z samochodem. Promem z Hiszpanii/Francji ~1h.",
    entryProcedure: "Kontrola dokumentów w porcie/na lotnisku."
  },
  "Republika Południowej Afryki": {
    country: "Republika Południowej Afryki",
    countryEn: "South Africa",
    documents: "Pozwolenie importowe, świadectwo zdrowia, test miareczkowania.",
    vaccinations: "Wścieklizna obowiązkowa. Test miareczkowania wymagany.",
    requirements: "Pozwolenie z DALRRD. Test miareczkowania min. 30 dni przed. Kwarantanna możliwa.",
    restrictions: "Kwarantanna domowa lub w ośrodku. Limit 6 zwierząt.",
    recommendations: "Piękny kraj, ale skomplikowane przepisy. Safari zazwyczaj nie pozwalają na psy.",
    entryProcedure: "Kontrola weterynaryjna i możliwa kwarantanna."
  },
  "Tunezja": {
    country: "Tunezja",
    countryEn: "Tunisia",
    documents: "Świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa, minimum 21 dni przed wjazdem.",
    requirements: "Świadectwo zdrowia wydane max 10 dni przed podróżą.",
    restrictions: "Brak zakazu ras. Hotele rzadko akceptują psy.",
    recommendations: "Popularny kierunek promami z Włoch. Sprawdź akceptację w hotelu.",
    entryProcedure: "Kontrola dokumentów w porcie/na lotnisku."
  },
  "Kenia": {
    country: "Kenia",
    countryEn: "Kenya",
    documents: "Pozwolenie importowe, świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane inne szczepienia.",
    requirements: "Pozwolenie z Kenya Veterinary Services. Świadectwo zdrowia.",
    restrictions: "Parki narodowe nie pozwalają na psy! Safari bez psów.",
    recommendations: "Psy nie są dozwolone w parkach narodowych i rezerwatach.",
    entryProcedure: "Kontrola weterynaryjna na lotnisku."
  },
  "Tanzania": {
    country: "Tanzania",
    countryEn: "Tanzania",
    documents: "Pozwolenie importowe, świadectwo zdrowia, szczepienie przeciw wściekliźnie.",
    vaccinations: "Wścieklizna obowiązkowa. Zalecane odrobaczanie.",
    requirements: "Pozwolenie z Tanzania Veterinary Services.",
    restrictions: "Parki narodowe zakazują psów! Serengeti, Ngorongoro - bez psów.",
    recommendations: "Safari bez psów. Zanzibar ma dodatkowe restrykcje.",
    entryProcedure: "Kontrola weterynaryjna na lotnisku."
  }
};

// Funkcja do generowania podstawowych danych dla krajów bez szczegółowych informacji
export const getDefaultTravelInfo = (country: string, countryEn: string): TravelInfo => ({
  country,
  countryEn,
  documents: "Międzynarodowe świadectwo zdrowia zwierzęcia, paszport weterynaryjny (jeśli dostępny), szczepienie przeciw wściekliźnie.",
  vaccinations: "Wścieklizna obowiązkowa - minimum 21 dni przed wjazdem. Zalecane: nosówka, parwowiroza, leptospiroza.",
  requirements: "Mikrochip ISO 11784/11785, aktualne świadectwo zdrowia wydane przez weterynarza.",
  restrictions: "Skontaktuj się z ambasadą lub konsulatem kraju docelowego, aby potwierdzić aktualne wymogi.",
  recommendations: "Sprawdź oficjalne źródła przed podróżą. Przepisy mogą się zmieniać. Zabierz kopie wszystkich dokumentów.",
  entryProcedure: "Kontrola dokumentów na granicy/lotnisku. Przygotuj wszystkie dokumenty w języku angielskim."
});

// Funkcja do pobrania informacji o kraju
export const getTravelInfo = (country: string): TravelInfo | null => {
  if (TRAVEL_DATA[country]) {
    return TRAVEL_DATA[country];
  }
  
  // Znajdź odpowiednik angielski
  const plIndex = COUNTRIES_PL.indexOf(country);
  if (plIndex !== -1) {
    const enCountry = COUNTRIES_EN[plIndex];
    if (TRAVEL_DATA[enCountry]) {
      return TRAVEL_DATA[enCountry];
    }
    return getDefaultTravelInfo(country, enCountry);
  }
  
  const enIndex = COUNTRIES_EN.indexOf(country);
  if (enIndex !== -1) {
    const plCountry = COUNTRIES_PL[enIndex];
    if (TRAVEL_DATA[plCountry]) {
      return TRAVEL_DATA[plCountry];
    }
    return getDefaultTravelInfo(plCountry, country);
  }
  
  return null;
};

// Funkcja do pobrania listy krajów posortowanej alfabetycznie w danym języku
export const getCountriesSorted = (language: "pl" | "en"): string[] => {
  const countries = language === "pl" ? [...COUNTRIES_PL] : [...COUNTRIES_EN];
  return countries.sort((a, b) => a.localeCompare(b, language));
};
